# backup:
# 	tar czvf backup-`date +%Y%m%d%H` /etc /tmp /mnt
# foldercreator:
# 	mkdir -p /world/us/illinois/chicago/5636
# cleanup:
# 	find / -type d -size +10G -name "*.mp4" -exec rm -rf {} \;

# step1:
# 		useradd bob 2> /dev/null 
# step2: step1
# 		sudo yum install lvm2 -y
# step3: step2
# 		sudo vgcreate VG1 /dev/sda
# step4: step3
# 		lvcreate VG1 --size 100K --name bob
# step5: step4
# 		mkfs.xfs /dev/VG1/bob
# step6: step5
# 		mount /dev/VG1/bob /home/bob

# morecommand:
# 		useradd tom
# 		mkdir /photos
# 		touch /tmp/somefile
# 		cat /etc/passwd

# all: step1 step2 step3 step4 step5 step6